using System;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using CommunityToolkit.Mvvm.ComponentModel;

namespace AIFileExplorer.ViewModels;

/// <summary>
/// ViewModel for a single node in the left-hand directory TreeView.
///
/// Replaces the old Models/DirectoryNode. Moving this into the ViewModel
/// layer means it can use ObservableObject and [ObservableProperty], which
/// gives us the key behaviour for Day 9: lazy loading triggered by expansion
/// rather than selection.
///
/// When the user clicks the expand arrow, Avalonia sets TreeViewItem.IsExpanded
/// = true. A style in MainWindow.axaml binds that back to this property.
/// The [ObservableProperty] generator then calls OnIsExpandedChanged, which
/// triggers the one-time disk read for this node's children.
/// </summary>
public partial class DirectoryNodeViewModel : ObservableObject
{
    /// <summary>
    /// Sentinel child added to any node that has subdirectories but hasn't
    /// been expanded yet. Its presence makes the TreeView show an expand
    /// arrow without reading the children from disk. Cleared immediately
    /// when LoadChildren() runs for real.
    /// </summary>
    public static readonly DirectoryNodeViewModel Placeholder =
        new("…", string.Empty);

    public string Name     { get; }
    public string FullPath { get; }

    /// <summary>
    /// Bound two-way to TreeViewItem.IsExpanded via a TreeView style.
    /// Setting this to true triggers OnIsExpandedChanged → LoadChildren().
    /// </summary>
    [ObservableProperty]
    private bool _isExpanded;

    public ObservableCollection<DirectoryNodeViewModel> Children { get; } = new();

    private bool _loaded;

    public DirectoryNodeViewModel(string name, string fullPath)
    {
        Name     = name;
        FullPath = fullPath;
    }

    // Generated by [ObservableProperty] — called after IsExpanded's setter runs.
    partial void OnIsExpandedChanged(bool value)
    {
        if (value) LoadChildren();
    }

    /// <summary>
    /// Reads immediate subdirectories from disk and populates Children.
    /// Idempotent — only runs once regardless of how often the node is
    /// expanded and collapsed.
    /// </summary>
    public void LoadChildren()
    {
        if (_loaded || string.IsNullOrEmpty(FullPath)) return;
        _loaded = true;
        Children.Clear();

        string[] subdirs;
        try   { subdirs = Directory.GetDirectories(FullPath); }
        catch (UnauthorizedAccessException) { return; }

        foreach (var dir in subdirs.OrderBy(d => d, StringComparer.OrdinalIgnoreCase))
        {
            var info  = new DirectoryInfo(dir);
            var child = new DirectoryNodeViewModel(info.Name, info.FullName);

            // Peek one level to decide whether this child needs its own
            // expand arrow (i.e. does it have grandchildren?).
            bool hasSubs = false;
            try   { hasSubs = Directory.GetDirectories(dir).Length > 0; }
            catch (UnauthorizedAccessException) { }

            if (hasSubs) child.Children.Add(Placeholder);
            Children.Add(child);
        }
    }
}
